### ISSUE TITLE
LSystem::get_replacement performance enhancement

### ISSUE THREAD

**Issue by JamesBremner** [Robin-Dillen/3DEngine#1]
https://github.com/Robin-Dillen/3DEngine/blob/72c7bea48778603407efe27f2f1e16d3beb7e280/l_parser.cpp#L554-L565

The performance of this looks problematical.  There are **five** calls to `find`  That is going to be very, very slow.  Have you time profiled this code?

There is not one line of documentation in this code!  So it is very hard to make out what it is doing.  However, whatever it is doing, there should be no need for so many calls to find.

Have you looked at the equivalent in my code?

https://github.com/JamesBremner/Lindenmayer/blob/6f23f6e338aee12833ac5e17ead36a362877c4a5/main.cpp#L42-L54

**Comment by JamesBremner** [comment]
> for the moment I have hardcoded the replace function,

What does this mean?  Does it mean you are not using the code you have posted?

**Comment by JamesBremner** [comment]
https://github.com/Robin-Dillen/3DEngine/blob/5b7d2e015bb96d5b0969138f0f2fc532b50a4987/l_parser.h#L191

This is the problem!  This will have a huge hit on performance.

I suggest you undo this change and return to using a simple map of chars to strings.

**Comment by Robin-Dillen** [comment]
I'm am using it, but I needed to temporarily hardcode some functionality to specify what was bottlenecking the code.

**Comment by JamesBremner** [comment]
> I have no idea how to implement stochastic L-systems 

Then remove this from the code.  It is killing your performance.  Return to using a simple map of chars to strings.

**Comment by Robin-Dillen** [comment]
Will do

**Comment by JamesBremner** [comment]
This commit to my fork 

fc51c471ca4c6baf09556be63db076ebfc499bd0

**Comment by JamesBremner** [comment]
I have fixed the build. However you have been hacking away at the master branch so the merge does not succeed.

( Do you need a tutorial on how to develop code collaboratively? )

**Comment by Robin-Dillen** [comment]
Well, it probably wouldn't hurt, is there anything i can do to fix it?

**Comment by JamesBremner** [comment]
The essential thing is not to hack away at the master.

Each person writing code works in his own branch or fork.  When code is ready to be pulled, it is merged into the master by the repository owner ( that's you! )

**Comment by JamesBremner** [comment]
The simplest thing probably to do now is to move your changes into a branch and rest the master to 72c7bea48778603407efe27f2f1e16d3beb7e280

However, since you are unfamiliar with github that probably is not going to happen.

So, I think I will leave it with you.  You can look at my commits to give you some ideas of what needs to be done.

**Comment by Robin-Dillen** [comment]
I kinda know what a branch is, and how to make it and so on, but i have nog clue how to fork.

**Comment by JamesBremner** [comment]
You are the repo owner.  You do not need to fork.

**Comment by Robin-Dillen** [comment]
I think I added your changes to the main branch

**Comment by Robin-Dillen** [comment]
I will leave my new times once i can test but i can't run my programm (see issue 2). I will try to fix that en then get back to this

**Comment by Robin-Dillen** [comment]
end of expand: 2.90585s
Total time for generating the lines: 2.95089s
drawing lines took: 36.4434s
elapsed time write: 0.0149998s
elapsed time: 36.4784s
it took 36.4784s in total

Still super slow, comparing to your code... I don't understand why my expanding takes so much longer?

**Comment by JamesBremner** [comment]
As expected, drawing the lines is the performance problem. 

Have you implemented the performance improvement I suggested?

**Comment by Robin-Dillen** [comment]
It could be that I missed it, since i'm not used to working with github everything is kind of a chaos.

**Comment by JamesBremner** [comment]
I see that you have.

https://github.com/Robin-Dillen/3DEngine/blob/86b2bba56f20f046da4a6b63d1db2bba449e8031/Draw.h#L121

**Comment by Robin-Dillen** [comment]
running l_systems021.ini
end of expand: 2.91925s
Total time for generating the lines: 2.96129s
finding minmax and generating points took: 21.0825s
drawing lines on the 'canvas' took: 11.7037s
drawing lines took: 36.6805s
elapsed time write: 0.0159996s

it took 36.7164s in total

**Comment by JamesBremner** [comment]
So, let's look at the code that draw the lines.

https://github.com/Robin-Dillen/3DEngine/blob/86b2bba56f20f046da4a6b63d1db2bba449e8031/easy_image.cpp#L200-L234

Yikes!!!!!

No wonder your drawing is so slow.

**Comment by Robin-Dillen** [comment]
didn't write that code myself, and didn't come to reviewing it. Will look into it!

**Comment by Robin-Dillen** [comment]
Could you perhaps elaborate on why the draw function is "Yikes!!!!!". I looked at it, and i didn't really see any real problems. But I tried to write my own draw function and this is what I came up with:
`
// https://www.geeksforgeeks.org/program-find-line-passing-2-points/
    /*if (x0 > x1) {
        //flip points if x1>x0: we want x0 to have the lowest value
        std::swap(x0, x1);
        std::swap(y0, y1);
    }
    int a = y1 - y0;
    int b = x0 - x1;
    int c = a * (x0) + b * (y0);
    auto equation = [a, b, c](int x){return roundToInt((double)(-a)/b * x + ((double)c/b));};

    for (int x = x0; x <= x1; x++){
        (*this)(x, equation(x)) = color;
    }*/`
    But this didn't really work, and somethimes crashed (depending on the number of iterations). Furthermore, it was even slower..

**Comment by JamesBremner** [comment]
Why would you imagine that writing individual pixels was a good idea?  For each and every pixel you have to execute

` auto equation = [a, b, c](int x){return roundToInt((double)(-a)/b * x + ((double)c/b));};`

which is going to take for ever.

Here is the code to draw a line segment on a windows machine.

```
    /** Draw line between two points
        @param[in] v vector with x1, y1, x2, y2
    */
    void line( const std::vector<int>& v )
    {
        MoveToEx(
            myHDC,
            v[0],
            v[1],
            NULL
        );
        LineTo(
            myHDC,
            v[2],
            v[3] );
    }
```

**Comment by Robin-Dillen** [comment]
Firstly, the program will also need to compile on linux. Secondly, what are the functions moveToEx and LineTo? Are they windows api calls? Because if they, I don't think I'm allowed to use them.

**Comment by JamesBremner** [comment]
>  Are they windows api calls?

Yes.

>  I don't think I'm allowed to use them. 

That's just crazy.

You are going to have to make a decision:

A:  Do you want to develop a high performance application using the best available tools?  I can help you with this one

B: Do you want a pathetic limping application that is artificially limited by arbitrary restrictions? 

Which effort A or B do you think will be a more useful learning experience?

**Comment by Robin-Dillen** [comment]
Even if we were allowed to use the windows api, I would still need to be able to compile and run on linux...

**Comment by JamesBremner** [comment]
You understand, I hope, that the windows and linux graphics are totally different?  To work around that you need to employ a cross-platform graphics library.  The snags are:

1.  Apparently you are not allowed to use such libraries.
2. Doing this is intrinsically slow, since every call has to be translated to the OS that is currently being used.

**Comment by Robin-Dillen** [comment]
Well, the way they implemented it, is just having a vector of all the pixels, and then just writing to a .bmp file. 
https://github.com/Robin-Dillen/3DEngine/blob/161b21c57b91ec19628e77c7156f18c6c6fd484e/easy_image.cpp#L250-L363
So, maybe graphics library was exaggerated. Its more like a image generator, I guess. And since we're only writing to a bmp file, the graphics aren't diffirent I think.

**Comment by JamesBremner** [comment]
And doing things this way is incredibly slow.  Manipulating individual pixels to draw a line segment is crazy.  That is what your graphics chip is for.

**Comment by Robin-Dillen** [comment]
I know it really is a shame.. The computers where they test the engine don't even have graphics chips(its some sort of docker I think)

**Comment by Robin-Dillen** [comment]
But I can't go around it, otherwise I would probably get a 0 and that's not what I want. So I'm stuck with the code they gave me, and everything that I can write myself.
