### ISSUE TITLE
non ending loop?

### ISSUE THREAD

**Issue by Robin-Dillen** [Robin-Dillen/3DEngine#2]
std::cout << ps.size() << std::endl;
    int i = 0;
    for (std::_List_const_iterator<Point2D> point = ps.begin(); point != ps.end(); point++) {
        if (i == ps.size() - 1){
            std::cout << "end" << std::endl;
            break;
        }
        i++;
        std::_List_const_iterator<Point2D> point2 = point++;
        img.draw_line(roundToInt(point->x * d + dx), roundToInt(point->y * d + dy), roundToInt(point2->x * d + dx),
                      roundToInt(point2->y * d + dy), line_color.convert());
    }
this loop in Draw.h line 57 wont end for some reason..

**Comment by JamesBremner** [comment]
You seem to have the line number wrong.

It helps a lot if you use the permalink to quote code.  Like this:

https://github.com/Robin-Dillen/3DEngine/blob/6c779f86093b5de705c6ede0367b39e6e86e2c59/Draw.h#L107-L118

**Comment by JamesBremner** [comment]
`std::_List_const_iterator<Point2D> point2 = point++; `

This is your problem.  You are incrementing the iterator!

**Comment by Robin-Dillen** [comment]
Oh, should've seen that...But doesn't quite explain why my loop wont end... It seems to be related with deleting PointSnake.

**Comment by JamesBremner** [comment]
You loop never exits because` point != ps.end()` is never false because you have incremented the loop iterator inside the loop.

**Comment by Robin-Dillen** [comment]
https://github.com/Robin-Dillen/3DEngine/blob/6c779f86093b5de705c6ede0367b39e6e86e2c59/Draw.h#L107-L114

thats why i added this, so it would certainly end, still doesn't work.

**Comment by JamesBremner** [comment]
That is very weird code.  You should fix the problem that increments the loop pointer.

**Comment by Robin-Dillen** [comment]
normally I fixed it. pushed into master(The problem should be renamed to non ending function, because the loop ends now)

**Comment by JamesBremner** [comment]
The loop looks much better.  

However, you are scaling and panning each point twice.  This will run faster:

```
bool first = true;
int xold, yold, xnew, ynew;
for( auto& point : ps )
{
    if( first )
    {
        first = false;
        xold = roundToInt(point->x * d + dx);
        yold = roundToInt(point->y * d + dy);
        continue;
    }
    xnew = roundToInt(point->x * d + dx);
    ynew = roundToInt(point->y * d + dy);
    img.draw_line(
        xold, yold
        xnew, ynew,
        line_color.convert());
    xold = xnew;
    yold = ynew;
}

```

**Comment by Robin-Dillen** [comment]
Thanks for the improvement, I have implemented the new loop. But it still doesn't work.. I'm going to check if destructors are the problem but normally i have a default destructor for everything. I will also add comments along the way to make it easier to understand.

**Comment by JamesBremner** [comment]
> it still doesn't work

What doesn't work?

I think you said the loop is OK now, and something else doesn't work.  In which case you should close this issue abd open a new one for the new problem.
