### ISSUE TITLE
std::list<Point2D> not deleting properly

### ISSUE THREAD

**Issue by Robin-Dillen** [Robin-Dillen/3DEngine#3]
The delete of the list gets stuck inside a loop inside the stl files

**Comment by Robin-Dillen** [comment]
https://github.com/Robin-Dillen/3DEngine/blob/b177bb2f1511351e8abe9529c2703c136bff7afa/Draw.h#L63
is not deleting properly

**Comment by Robin-Dillen** [comment]
when std::list<Point2D> is replaced by std::vector<Point2D>, things go as planned...

**Comment by JamesBremner** [comment]
> is not deleting properly

Please describe what happens.  This issue description is almost meaningless.   What actually happens?

**Comment by JamesBremner** [comment]
https://github.com/Robin-Dillen/3DEngine/blob/b177bb2f1511351e8abe9529c2703c136bff7afa/Draw.h#L63

This is declared, but it does not seem to be used anywhere

**Comment by Robin-Dillen** [comment]
ps is my container where i store all my points, It's just used in the draw function

**Comment by JamesBremner** [comment]
What are you storing your points in a list?  There is a significant overhead in using a list, but it seems to me that a  vector would provide all the features you need.

**Comment by Robin-Dillen** [comment]
I though a list was good for iteration. A vector would probably be more easy, I could also track the size and make an array,would that be faster?

**Comment by JamesBremner** [comment]
> when std::list is replaced by std::vector things go as planned..

Then your fix is to use the simpler container.  Not only will things "go as planned" but they will go faster too.

**Comment by JamesBremner** [comment]
You are too much in love with complexity.  Keep it simple.  Use a vector.

**Comment by Robin-Dillen** [comment]
Yeah, I still got alot to learn. Thanks for helping me out like this!

**Comment by Robin-Dillen** [comment]
This is off-topic, but i want to store my L-string, in a queue, so I never store the same thing twice. I noticed in task manager that my memory went over 2GB, and thats not allowed.
