### ISSUE TITLE
L-string storage.

### ISSUE THREAD

**Issue by JamesBremner** [Robin-Dillen/3DEngine#4]
> but i want to store my L-string, in a queue, so I never store the same thing twice. 

( asked in issue #3 )

The Lstring should be stored in a string.  

There is no reason to do anything more complex.

**Comment by Robin-Dillen** [comment]
I will keep it a string, exept if I go over the 2GB then I need to find a solution. as Knuth said  “Premature optimization is the root of all evil”

**Comment by JamesBremner** [comment]
The Lstring consumes less than 2 bytes per line segment.  Your point storage consumes way more.  If your string is too long to be stored, then the rest of your code will need even more storage, no matter how complicated your string storage.

Do you really need to handle Lstrings that will be longer then a billion bytes?  I doubt that you program will be able to cope with strings a thousand times smaller than that.

**Comment by Robin-Dillen** [comment]
Yeah, i wanted to do it because of my point storage. So that at least I only store one of the two. I'm thinking if there is any way to avoid the storing of the points, but i can't think of anything..

**Comment by JamesBremner** [comment]
.> I'm thinking if there is any way to avoid the storing of the points, but i can't think of anything..

Just do no store the line points.  It achieves nothing except keeps a duplicate od the same data in a much less compact method.

The drawing function can parse the Lstring as it goes along.  Sis you not see that in my code?

**Comment by Robin-Dillen** [comment]
I saw that in your code, but then is the question: how can i find the minmax of an L_string

**Comment by JamesBremner** [comment]
Good question.

You will have to add a function that does a quick parse of the string, doing no drawing or storing or anything but only recording the min and max of both x and y.  Should run very fast.

**Comment by Robin-Dillen** [comment]
But then the only things i would need to do is: remove adding of the points and adding the switch block to the draw function, i think. I'm going to try that(I may be horribly wrong though)

**Comment by JamesBremner** [comment]
You will also need to find a decent graphics library.  I would, of course, recommend my own

```C++
void Draw( const std::string& plant )
{

    // construct top level application window
    wex::gui& form = wex::maker::make();
    form.move({ 50,50,800,800});

    form.events().draw([&]( PAINTSTRUCT& ps )
    {
            // ( parse the Lstring ... )

            S.line( { x,y,x+xinc,y+yinc});
        }
    });
    // show the application
    form.show();

    //Pass the control of the application to the windows message queue.
    form.run();
```

**Comment by Robin-Dillen** [comment]
I would love a good library, but it's not allowed to use graphics libraries  ;)

**Comment by JamesBremner** [comment]
What do you mean "not allowed"?

**Comment by JamesBremner** [comment]
You cannot draw on the screen without using some graphics library.  This easyimage is some strange graphics library you must have dug up somewhere.  You could, I suppose, use the windows API directly.  That would be rather painful, though it would be fast.

FYI Windex, my graphics library is a thin wrapper around the windows API.

**Comment by JamesBremner** [comment]
https://github.com/JamesBremner/windex

**Comment by Robin-Dillen** [comment]
The purpose is not really drawing on the screen, its more for generating images and just writing the images to a .bmp file.
And it's not allowed because it's a school assignemen(but they would be happy with the code as I posted it since we have a max runtime of 30 minutes) , so it's more for fun that i'm investing this effort into optimizing!

**Comment by JamesBremner** [comment]
> The purpose is not really drawing on the screen, its more for generating images and just writing the images to a .bmp file.

Whichever.  Once you have the drawing on he screen it is trivial to save it to a BMP file.  Also, once you have a BMP file it is trivial to draw it on the screen.  To get to either situation, you need a graphics library.  The one you are using is hopeless.

**Comment by Robin-Dillen** [comment]
We are not allowed graphics libraries  that help in any way, so i would have to write it myself. So then i guess the best(easiest) thing would be to use this library as a foundation and improve the code(so keep the structure)?

**Comment by JamesBremner** [comment]
> We are not allowed libraries that help in any way(with graphics

You are using easyimage.  Why is that allowed?

> so i would have to write it myself

Write what?  A graphics library?  

> the best(easiest) thing would be to use this library 

Which library are you referring to?

( You often write "it" and leave me to guess what you ere referring to! )

**Comment by Robin-Dillen** [comment]
Why received the easyimage library, it's the only one we can use. I indeed meant, writing my own graphics library. It would be easiest I guess to use the easyImage library as a foundation (for the structure) and just improve/rewrite its functions.
